// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:464967415855:web:bfe7dde715d003d58e6eda',
    messagingSenderId: '464967415855',
    projectId: 'fireapp-ce31d',
    authDomain: 'fireapp-ce31d.firebaseapp.com',
    storageBucket: 'fireapp-ce31d.appspot.com',
    measurementId: 'G-LNBTWHLXE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAU9dydVNKlTiRefEIodrVxrrSVq5RneM',
    appId: '1:464967415855:android:66a33926ae415bb68e6eda',
    messagingSenderId: '464967415855',
    projectId: 'fireapp-ce31d',
    storageBucket: 'fireapp-ce31d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwv0Nbccd3I6C0p3XtqYx6ZJ0AACh8QDc',
    appId: '1:464967415855:ios:1f5b24d2fad75ae78e6eda',
    messagingSenderId: '464967415855',
    projectId: 'fireapp-ce31d',
    storageBucket: 'fireapp-ce31d.appspot.com',
    androidClientId:
        '464967415855-r3i3rk0ocr1lne1tmtbh6fkdt4bm8hgr.apps.googleusercontent.com',
    iosClientId:
        '464967415855-livvg5b48rkr6sfdbv52da32c26kpj1s.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
